### ISSUE TITLE
[feature/dataflow] Data flow analysis doesn't propagate annotations around out parameters

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1074]
The analysis needs to treat `out` parameters the same way it does return values.
Similar problem with `ref` parameters as well, although those are more complicated.

**Comment by MichalStrehovsky** [comment]
My line of thinking is that we should just disallow annotating `out` and `ref` parameters (there's no difference between those two at the IL level, so if one of them is more complicated, it's all more complicated).

Same for `ref` locals. Loading from a ref location would lose all annotations and therefore we don't need to track stores.

I can't think of good use cases for why this would be needed and it will simplify the internal handling (we can delete the `StackSlot` struct and treat values on the evaluation stack as instances of `ValueNode` only).

Otherwise this would mostly be about implementing the IsByRef TODOs in the method body scanner and increasing our test matrix to cover that.

**Comment by vitek-karas** [comment]
@eerhardt ran into this on https://github.com/dotnet/runtime/blob/234b07449a6473cc3b2ddeb2910179bcc44db95e/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs#L332-L337. So it's not fictional unfortunately.

**Comment by MichalStrehovsky** [comment]
Sigh. That answers whether we can optimize out `StackSlot`. We can't.

We might also need to add more things to the DynamicallyAccessMembers enum to make that code in S.T.Json work. That one is not because of `out`, but because of `IsAssignableFrom`. Linker is currently happy to strip interface lists and replace bases of kept type with `System.Object` if it thinks it can get away with it (i.e. the type wasn't allocated at runtime). Doing that breaks `IsAssignableFrom` if the type wasn't allocated though. I'll file tracking issue.

**Comment by vitek-karas** [comment]
Fixed by https://github.com/mono/linker/pull/1083
