### ISSUE TITLE
Add --ignore-substitutions command line option

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#1152]
the option should work same way as `--ignore-descriptors` but for embedded substitutions instead

**Comment by sbomer** [comment]
Is it also worth changing '--strip-resources' to '--strip-descriptors' and '--strip-substitutions'? Or do you think they will be used together anyway?

**Comment by marek-safar** [comment]
They have a different purpose and both are advanced control flags which should be possible to control independently

**Comment by sbomer** [comment]
Fixed in https://github.com/mono/linker/pull/1146/commits/2da9ccf920ad0214416e0b6f94c82bc1ca640ee6. That gets rid of `--strip-resources`. Are you aware of anyone who would be taking a dependency on that argument? Should I keep it around (mapping to the same thing as `--strip-descriptors`) for backwards compatibility?

**Comment by marek-safar** [comment]
Yep, that's fine to remove `--strip-resources`
