### ISSUE TITLE
Fix inconsistencies in error formatting

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1158]
Related to https://github.com/mono/linker/issues/1153, but I made a new issue for this because it's not about the contents of the messages.

Here's an example of what gets logged today:
<img width="623" alt="Screen Shot 2020-05-01 at 8 55 20 PM" src="https://user-images.githubusercontent.com/787361/80854524-12ac9900-8bee-11ea-9c0e-eecf783738f3.png">

The first line is from the new error logging, and the second line from the old. The inconsistent prefixes will go away once all warnings/errors get moved to the new logging APIs, but I'd make two suggestions:
- Use `ILLink` instead of `illinker`
- Ensure that our warnings all use single quotes instead of double quotes

**Comment by vitek-karas** [comment]
@mateoatr I assume this is fixed now - can you please double check and close?

**Comment by sbomer** [comment]
Since we've been discussing naming conventions, do we feel that 'ILLink' (or 'illinker'?) is the right prefix here? @eerhardt

**Comment by mateoatr** [comment]
I had already checked that we were only using `ILLink` and single quotes. I just double checked. The only inconsistency I've seen is that sometimes we write the name of custom attributes between grave accents ('`'), and sometimes we just use the name of the cas (without any sort of quotes).

e.g.:
https://github.com/mono/linker/blob/master/src/linker/Linker.Dataflow/FlowAnnotations.cs#L286
https://github.com/mono/linker/blob/master/src/linker/Linker.Steps/MarkStep.cs#L691

**Comment by vitek-karas** [comment]
> Since we've been discussing naming conventions, do we feel that 'ILLink' (or 'illinker'?) is the right prefix here?

I think it's fine - I know there's a bit of a confusion, but there's at least a system to it:
* The capability/feature is "trim" - the general tool to implement this is "trimmer"
* The actual implementation of the feature is in ILLink - the tool is "ILLinker"

So MSBuild properties are called "Trim" since they're talking about the capability. Warnings/Errors are called "ILLinker" since they are comming from "ILLinker".

It's similar to for example Compile/csc
* The capability is compilation
* The actual implementation is "csc"

So MSBuild properties are called "compile" (mostly), but the errors are all "CSC".

**Comment by marek-safar** [comment]
> I think it's fine - I know there's a bit of a confusion, but there's at least a system to it:

I think this is worth documenting perhaps even on the doc entry page https://github.com/mono/linker/tree/master/docs

**Comment by vitek-karas** [comment]
I agree with @marek-safar that we should document the terminology:
What is trimming (post-build step which optimizes the app for size) and what are the tools used by the SDK to implement the trimming (ILLink, ILLinker).

**Comment by vitek-karas** [comment]
This should now be fully fixed.
