### ISSUE TITLE
Support for LinkerRemovableAttribute

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#1162]
Once #1118 is completed we should extend it further to allow specifying "always" removed attributes. This is will be used for the final app mode of linker where some of the attributes can be always removed but we don't want to hardcode them in the linked. The idea is to have them annotated in the code or inside the custom attribute annotations.

Custom Attributes to be included in the list
- all nullable attributes
- System.CLSCompliantAttribute
- System.Security.UnverifiableCodeAttribute
- etc (the full list will be collected separately and might be RID specific)

Proposal of how it can look like when building on top of #1118 

```xml
<linker>
  <assembly fullname="System.Private.CoreLib">
    <type fullname="System.CLSCompliantAttribute">
		<attribute FullName="System.LinkerRemovableAttribute" AssemblyName="System.Private.CoreLib">
		</attribute>
    </type>
  </assembly>
</linker>
```

The attribute name `System.LinkerRemovableAttribute` will be the only name hardcoded in linker which will remove all attributes usages but not the attribute definition.

To make this even more effective and to allow removing attributes which are feature linker the XML format should be extended to support `feature` and `featurevalue` attributes like in [substitutions format](https://github.com/mono/linker/blob/master/docs/data-formats.md#conditional-substitutions)

```xml
<linker>
  <assembly fullname="Assembly">
    <type fullname="System.Runtime.InteropServices.GuidAttribute" feature="COM" featurevalue="false">
		<attribute FullName="System.LinkerRemovableAttribute" AssemblyName="System.Private.CoreLib">
		</attribute>
    </type>
  </assembly>
</linker>
```

**Comment by vitek-karas** [comment]
The name of the attribute can remain internal for now (as we don't expect people outside of runtime/CoreFX to need to specify this) - but we should think about the name. The typical discussion of having the name of the tool in the attribute name.

Additionally, some attributes are auto-generated into the target assembly, so they don't have a well defined "declaring" assembly. Good example are the nullable attributes `NullableAttribute`, `NullableContextAttribute`, .... They can be defined in the assembly where they are needed. From the point of view of the linker there will be several `TypeDefinition` instances all representing for example `NullableAttribute` from different assemblies. To handle this the XML syntax would need to support something like a wildcard for assembly, so for example:
```XML
<linker>
  <assembly fullname="*">
    <type fullname="System.Runtime.CompilerServices.NullableAttribute">
      <attribute fullname="System.LinkerRemovableAttribute" />
    </type>
  </assembly>
</linker>
```

**Comment by marek-safar** [comment]
> To handle this the XML syntax would need to support something like a wildcard for assembly

Or alternatively not to make the assembly `fullname` mandatory

```xml
<linker>
  <assembly> <!-- means any assembly -->
    <type fullname="System.Runtime.CompilerServices.NullableAttribute">
      <attribute fullname="System.LinkerRemovableAttribute" />
    </type>
  </assembly>
</linker>
```

**Comment by vitek-karas** [comment]
Based on several offline discussions we decided to not have an attribute for this in the CoreLib (basically postpone dotnet/runtime#38301). The functionality will be in linker only, based on the XML files.

What remains to be decided is the exact syntax.

### 1 - Use fake attribute type
The syntax in the XML would remain as noted above, so something like:
```XML
<linker>
  <assembly> <!-- means any assembly -->
    <type fullname="System.Runtime.CompilerServices.NullableAttribute">
      <attribute fullname="System.LinkerRemovableAttribute" />
    </type>
  </assembly>
</linker>
```

The implementation would recognize this as a special case and handle it appropriately - it would not require the existence of the `LinkerRemovableAttribute` type in the input assemblies.

Pros:
* No new syntax

Cons:
* If in the future we decide to introduce a real attribute type in CoreLib there will be problems with reconciling that with the one used here - potentially different naming, constructor arguments and so on...

### 2 - New syntax in linker attributes XML
The idea is to introduce a new syntax into the linker attributes XML - basically make this a special case even in the syntax. One such way would be to add `remove` XML attribute like this:
```XML
<linker>
  <assembly> <!-- means any assembly -->
    <type fullname="System.Runtime.CompilerServices.NullableAttribute" remove="true" />
  </assembly>
</linker>
```

Pros:
* No future collisions with the actual attribute - internally we could switch to using the attribute once its available - basically we would make the new syntax equivalent to using the attribute (either in code or in the XML).

Cons:
* Special case just for this. Logically this functionality doesn't fit the linker attributes XML purpose.


### 3 - New syntax in the linker descriptor XML
This would be similar to 2, but we would add a new syntax to the descriptors, so something like this (the XML looks identical to 2, but this time it would be in descriptor XML):
```XML
<linker>
  <assembly> <!-- means any assembly -->
    <type fullname="System.Runtime.CompilerServices.NullableAttribute" remove="true" />
  </assembly>
</linker>
```

Pros:
* Logically fits better with the descriptor. Currently the descriptor makes things "included", this would add the capability to "exclude" them as well.

Cons:
* Somewhat problematic because anything mentioned in the descriptor gets rooted. It's not a big problem (linker doesn't mark assemblies mentioned in the descriptors, unless it ends up marking something from that assembly) and nested types are unlikely (there the parent type would be marked by linker without additional changes).
* We need the "any assembly" functionality to be able to remove compiler generated attributes (like the `NullableAttribute`) - adding this functionality to the descriptor is possible, but might be problematic from size perspective (if I "forget" to specify assembly it would just work, but potentially include much more code).

### 4 - New syntax in the linker substitutions XML
Linker substitutions already supports "removal" of method bodies. We could add a new syntax to remove types, so for example:
```XML
<linker>
  <assembly> <!-- means any assembly -->
    <type fullname="System.Runtime.CompilerServices.NullableAttribute" action="remove" />
  </assembly>
</linker>
```

Pros:
* Fits the substitution purpose relatively well
* We already have pretty much exactly the same functionality for resources `<resource name="Resource" action="remove"/>`
* The substitution XML already has special syntax for basically every action it can take, so adding a new one is natural.

Cons:
* Would have to enable "all assemblies" in the substitutions XML. This is not necessarily a disadvantage, I don't see much problems with this.

---------------------

I personally like 4 (substitutions) - we already have it there for resources, adding it for types is natural. 

I'm hesitant about 2 (attributes XML) - it feels "arbitrary" and doesn't fit the purpose of that XML. That said we could sell it as a special syntax for the future real attribute.

I don't like 1 (fake attribute) because of the potential problems in the future - that said we would have to deal with having "two ways to do a thing" anyway (no matter which solution we chose).

I also don't like 3 (descriptors XML), while it fits logically it has a potential of introducing backward compat problems with existing descriptors.

@marek-safar @sbomer for review and opinions

**Comment by marek-safar** [comment]
I agree that options 2 and 4 are preferable but I don't see 4 to be clearly better than 2. We do have a concept of remove action there which is close but it was not exact fit either.

We'd need to solve following if we want to go with 4 like approach

- Remove action is not accurate. The type could end up not being actually removed and attribute usage stripped only somewhere. A simple scenario for this would be when copied assembly references the attribute. This might be more mental/documentation problem.

- Allowing `action="remove"` on `<type>` means we'll need to write a lot of code to guard against miss-using it otherwise someone can write syntax like `<type fullname="System.Object" action="remove" />`.

- Are we going to disable `<type fullname="Assembly.A" feature="EnableOptionalFeature" action="remove">` so it does not collide with future feature based `LinkerRemovableAttribute` or are we going to support 3 different ways to do achieve same?

Alternatively, we could also make option 2 to be more about the addition. For example, something like this would work the same for feature-based and feature-less removals as `feature` and `featurevalue` are optional. 

```xml
<linker>
  <assembly> <!-- means any assembly -->
    <type fullname="System.Runtime.CompilerServices.NullableAttribute">
		<attribute builtin="removable" feature="EnableOptionalFeature" featurevalue="false" />
	</type>
  </assembly>
</linker>
```

**Comment by vitek-karas** [comment]
Had an offline discussion with @marek-safar on this...
* I agree that in solution 4 (substitutions) `action="remove"` is wrong - it would have to be something like `action="remove attribute instances"` - not very nice
* We think (hope) that eventually (.NET 6 maybe) we will add a real attribute for this into CoreLib
* Future collisions between potentially multiple ways to specify similar behavior will exist already as linker will have to be able to handle possibly multiple sources for the same thing (even with substitutions, the same substitution can come from two different XML files) - considering future real attribute, it would make sense to have this collision resolution located only in one XML format.

Outcome:
Go with solution 2 (attribute XML) with a special syntax which will otherwise behave as an attribute (there just won't be a matching real type for it). So basically what was proposed above, I would just change the naming a little bit:
```XML
<linker>
  <assembly> <!-- means any assembly -->
    <type fullname="System.Runtime.CompilerServices.NullableAttribute">
      <attribute internal="RemoveAttributeInstances" feature="EnableOptionalFeature" featurevalue="false" />
    </type>
  </assembly>
</linker>
```
