### ISSUE TITLE
Warning for references to explicitly removed attributes

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#1163]
The outcome of the attribute removal should be predictable and therefore we need to issue a new warning when any of the removed attributes is still referenced in the user code. This should apply in all cases where the attributes are explicitly removed (for example as part of #1162).

**Comment by vitek-karas** [comment]
We should also think about scenarios where the attribute is not referenced via type-ref. Maybe we won't be able to solve it, but we should see if there's something we can do about this. An example of code which would still be wrong:
```C#
foreach (var a in myType.GetCustomAttributes()) {
    if (a.Name == "NullableAttribute" && a.Namespace == "System.Runtime.CompilerServices") {
        // Do something which should never happen in linked app - and thus be broken
    }
}
```

Maybe we should simply mark unconditional `GetCustomAttributes` as a problematic API.

/cc @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
I think you know my stance on attribute removal... It's pretty problematic.

For the nullable ones, things like EF are already reading the nullable attributes and because the identity of these attributes is based on a name match, they use the catch-all APIs to enumerate them.

There's a proposal to add official APIs to read these annotations that we could key off at some point but it will require more sophistication in the linker. https://github.com/dotnet/runtime/issues/29723

**Comment by vitek-karas** [comment]
@tlakollo  - I think this was already done as part of #1307 - please close this issue if that's the case.

**Comment by tlakollo** [comment]
Yup that is the case
