### ISSUE TITLE
Support feature conditions on XML descriptors

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1268]
This would allow us to use the embedded ILLink.Descriptors.xml to root "global" dependencies for which we don't have a great place to put `DynamicDependencyAttribute`, while allowing them to be linked out using feature settings. From discussion with @vitek-karas, it sounds like this will be useful for removing debugger support, COM, etc.

@marek-safar what do you think of this?

**Comment by vitek-karas** [comment]
I'm all for doing this 😄

**Comment by marek-safar** [comment]
I agree that this would be a useful extension of XML descriptors.

**Comment by eerhardt** [comment]
If we take this approach, we should be able to close https://github.com/dotnet/runtime/issues/37352, right?

The motivation behind https://github.com/dotnet/runtime/issues/37352 was being able to "root" types globally, but also conditionally. See the discussion here: https://github.com/dotnet/runtime/pull/37288#discussion_r434018579.

So if there are scenarios where we need to preserve a type globally under certain conditions (Debug, COM, JS, etc), we can use the XML descriptor + feature switch mechanism, instead of putting a `[DynamicDependency("foo", Condition = "feature switch")]`.

Note that the advantage of having `[DynamicDependency]` on the Type vs having a global XML descriptor, is that the global XML descriptor will keep the dependency even if the `Type` isn't being used. With the `[DynamicDependency]` on the Type approach, if the whole Type could be trimmed, so could its dependencies.

**Comment by marek-safar** [comment]
> So if there are scenarios where we need to preserve a type globally under certain conditions (Debug, COM, JS, etc), we can use the XML descriptor + feature switch mechanism, instead of putting a [DynamicDependency("foo", Condition = "feature switch")].

This scenario should be used only for cases where the source of the dependency is outside of src/libraries (e.g. external code, different runtime, etc) for anything else `DynamicDependency` is the preference

> global XML descriptor will keep the dependency even if the Type isn't being used.

That's not true. See https://github.com/mono/linker/blob/master/docs/data-formats.md#preserve-a-type
