### ISSUE TITLE
IL2045 for blazor app

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1371]
This warning will show up by default in every blazor app unless we silence it as part of https://github.com/dotnet/sdk/pull/12388. @tlakollo fixed a similar issue in https://github.com/mono/linker/pull/1332, for conflicting root descriptors and attribute removal directives. Here the conflict is between an assembly action and a removal directive.

The blazor defaults have some `copy` assemblies, which means that attribute instances in that assembly are kept, causing the attribute type to be kept (since https://github.com/mono/linker/pull/1344 I think).

We also have linker attribute [files](https://github.com/mono/linker/pull/1332) which say to remove attributes like `NullableAttribute`. When an attribute type is kept despite such a directive, we emit `IL2045`.

@vitek-karas @tlakollo

**Comment by vitek-karas** [comment]
I tried this and there are two cases where we generate 2045:
* The attributes themselves have self-references and those generate 2045 - this will be fixed by #1373 
* Code in stack trace processing relies on some of the removed attributes - this has been discussed and we want to leave it like that - so we will have to do something about this in the runtime (either suppress the warning or wrap the usage with the debugger feature switch)
