### ISSUE TITLE
Debug build of linker fails with ArgumentOutOfRangeException when assembly has methods on the <Module> type

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1526]
If an assembly has any method on the `<Module>` type linker will throw in debug builds from here:
https://github.com/mono/linker/blob/master/src/linker/Linker.Steps/MarkStep.cs#L1388

The reason is that the list of allowed reasons for marking a method doesn't contain `TypeInAssembly` which is used by the caller here:
https://github.com/mono/linker/blob/master/src/linker/Linker.Steps/MarkStep.cs#L1169

**Comment by MichalStrehovsky** [comment]
The code calling into this is also rather clumsy. Might want to clean that up as well.

https://github.com/mono/linker/blob/b89cb90abdfdc4e1ccd0822b62d367fa35d30f00/src/linker/Linker.Steps/MarkStep.cs#L1165-L1172

* We specifically care about preserving the class constructor on the module type, because that's the module initializer. I guess things end up happening somehow because the C# 9.0 `ModuleInitializerAttribute` works, but maybe we should be more explicit about what this is doing so that it makes sense to the reader.
* We should check if Cecil has API to find the "Module" type. The name `<Module>` is how the C# compiler names this, but what matters to the runtime is that this is the type with RID 1 (TypeDef 02000001). Linker shouldn't hardcode compiler implementation details.

**Comment by marek-safar** [comment]
The comparison could be changed to `type.MetadataToken.RID == 1`
