### ISSUE TITLE
Expand DynamicDependencyAttribute target to include interfaces

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#1570]
We have existing code in XI which uses custom way to mark dependencies which are not visible to the linker (custom metadata loading with no reflection involvement). The code pattern looks like

```c#
	[SomeSpecialAttribute (PropertyType = typeof (SomeWrapper))]
	public interface IA
	{
	}

	public class SomeWrapper
	{
		public SomeWrapper (int arg1, string 2)
		{
		}
	}
```

The intention is to keep/mark `SomeWrapper::SomeWrapper (int arg1, string 2)` when IA is kept. This should be easily doable if we could place DynamicDependency on the interface type like this

```c#
	[SomeSpecialAttribute (DependencyType = typeof (SomeWrapper))]
	[DynamicDependency (typeof (SomeWrapper), ".ctor")]
	public interface IA
	{
	}
```

@rolfbjarne @vitek-karas @MichalStrehovsky

**Comment by vitek-karas** [comment]
Is the requirement that if the interface is marked (for whatever reason), then include the other thing as well?
Or could we instead tie to a method on the interface? (not that it makes a bug different I think).

This would be a very simple change in the linker - we would also have to modify the attribute in CoreLib as currently it can only be used on method/field.

In general we would like everybody to put the attribute onto a method as that kind of makes sense (the method does something which requires the dependency). Putting it on a type is not very intuitive (the type alone can't do anything which would require the dependency).

If we were to do it I would allow the attribute on all types (not just interfaces).

**Comment by marek-safar** [comment]
> Putting it on a type is not very intuitive 

I agree, in reality, the dependency should fire when there could be at least one type which can carry the contract (interface) but I'm not sure we want to go with the different attribute type.

**Comment by rolfbjarne** [comment]
> Or could we instead tie to a method on the interface?

The interface might be empty.

**Comment by MichalStrehovsky** [comment]
How many constructors has `SomeWrapper`? Would it be a problem if we were to keep all the public constructors of the type referenced from `[SomeSpecialAttribute (PropertyType = typeof (SomeWrapper))]`?

If it's okay, this can already be annotated with the dataflow annotations we're introducing in .NET 5:

```csharp
class SomeSpecialAttribute
{
    // Asks the linker to keep all public ctors on types assigned to this property
    // This includes assignments done by application of custom attributes
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]
    public Type PropertyType { get; set; }
}
```

If `SomeSpecialAttribute` is annotated like above, linker will keep all the public constructors of `SomeWrapper` in the above example.

**Comment by rolfbjarne** [comment]
> If `SomeSpecialAttribute` is annotated like above, linker will keep all the public constructors of `SomeWrapper` in the above example.

We want to link `SomeSpecialAttribute` away, because it's not needed at runtime.

**Comment by MichalStrehovsky** [comment]
> We want to link SomeSpecialAttribute away, because it's not needed at runtime.

That feels orthogonal to what is discussed in this issue.

**Comment by marek-safar** [comment]
> If it's okay, this can already be annotated with the dataflow annotations we're introducing in .NET 5:

I don't think dataflow annotations are helpful here. They work with reflection only which is not the scenario here.

**Comment by MichalStrehovsky** [comment]
> I don't think dataflow annotations are helpful here. They work with reflection only which is not the scenario here.

They serve two purposes: 

1. Keep stuff
1. Make it possible for linker to reason about reflection API use.

Using them to achieve 1 is legit. Is there something that would prevent us from using the existing API?

**Comment by MichalStrehovsky** [comment]
(There's a reason why neither DynamicDependency nor DynamicallyAccessedMembers talk about reflection. They can be used to describe any sort of dynamic access pattern. Reflection is one. Other is interop. And there's more in special embedding scenarios like Xamarin and Unity. Linker uses them as hints for reflection dataflow analysis, but that's not their primary purpose).

**Comment by marek-safar** [comment]
Are you sure this is going to work because there won't be any flow analysis involved? The attribute `SomeSpecialAttribute` is only declaratively placed on the type and never enquired in the code

**Comment by MichalStrehovsky** [comment]
Linker needs to blindly respect the attribute because the fact that there's the attribute means that there's going to be an access pattern that linker can't analyze - it's the definition of the attribute.

We don't try to postpone this until there's a "sink" (place of actual dynamic access). It's computationally intensive to find the sink and the sink will often not be visible anyway (it could be behind lot of layers or a thing like what Xamarin does that linker really has no clue about because it happens somewhere else).

**Comment by vitek-karas** [comment]
Currently linker doesn't work like that with attributes. Most notably, if the attribute is annotated for removal linker will not process any of the annotations on the attribute itself because currently the implementation couples the annotation processing with marking.

We could decouple these if we think that's the right thing to do. This is a bit of a problematic topic:
* Other attributes which are meant for linker alone like `DynamicallyAccessedMembersAttribute` are marked for removal, but linker first uses the information they convey and only then removes them. Their effectiveness is not tied to their removal in any way.
* On the other hand annotations on methods/fields do not behave like that - those are only effective if the annotated method/field is marked (not removed).
* There are attributes which would look very similar to the one proposed here, but we want the opposite behavior. For example `DebuggerTypeProxyAttribute` - this takes a `Type` parameter in its .ctor as well and it has data flow annotation to [preserve the entire type](https://github.com/dotnet/runtime/blob/142021c172e2e3b60d6c7e58a4e514002f1679c5/src/libraries/System.Private.CoreLib/src/System/Diagnostics/DebuggerTypeProxyAttribute.cs#L13-L14). But we don't want to do that unless the attribute itself is kept. For example if `DebuggerSupport` feature switch is turned off, the attribute should be removed and the type it points to should not be marked either.

So far the general design of the data flow annotations has been that they're tied to some other piece of the application (method, field, ...). And they are only effective if that piece is marked (will be included in the application). In this specific case it seems the piece of the application which the annotation should be tied to is the interface type or ideally it's instantiation - so the annotation should be added there.

If it was a class/struct the right place to put this would be on the .ctor - as that clearly ties it to the instantiation of the type - and in that case the right attribute to use would be `DynamicDependencyAttribute` because the target of the dependency is not used in any way by the actual IL.

For interfaces this won't work as they don't have a .ctor - so we would either have to allow `DynamicDependencyAttribute` on the interface type like this issue proposes, or come up with some other solution.

Is my understanding correct that the `SomeSpecialAttribute` which Xamarin uses here is there basically to serve the same purpose as `DynamicDependencyAttribute`? As in one can be replaced by the other? Or does it have some other meaning as well?

**Comment by rolfbjarne** [comment]
> Is my understanding correct that the `SomeSpecialAttribute` which Xamarin uses here is there basically to serve the same purpose as `DynamicDependencyAttribute`? As in one can be replaced by the other? Or does it have some other meaning as well?

The attribute has other meanings as well, so it can't be replaced with DynamicDependencyAttribute (but we could easily add DynamicDependencyAttribute (or some other attribute) if the linker needs that to work).

**Comment by vitek-karas** [comment]
What other meaning does the attribute have if it's not supposed to survive linking?

**Comment by rolfbjarne** [comment]
> What other meaning does the attribute have if it's not supposed to survive linking?
> Or rather - what other tool uses the attribute (before linker)?

The attribute is used to mark that a managed interface represents an Objective-C protocol.

Example:

```csharp
[Protocol (Name = "MyProtocol", WrapperType = typeof (MyProtocolWrapper)]
interface IMyProtocol {
}
class MyProtocolWrapper : IMyProtocol {
    MyProtocolWrapper (IntPtr handle, bool owns) { ... }
}
```

When we build a Xamarin.iOS app, we process all the assemblies and create a table of all such interfaces, and their corresponding wrapper types. The resulting table is stored in native code (it's a simple lookup table: metadata token for interface => metadata token for wrapper class). At runtime, when we need to figure out which managed type to instantiate given a native object that implements a particular Objective-C protocol, we check the table and create an instance of the corresponding wrapper class.

This means that:

* We don't need the Protocol attribute at runtime (we already have all the information it represents in other ways), so we'd like to link it away.
* We need the MyProtocolWrapper class.

**Comment by vitek-karas** [comment]
Thanks a lot for the explanation.

One possible workaround: Since we're already processing the assembly before linker (to extract the information we inject into native code) we could also generate a descriptor.xml which will root all of the wrapper classes and feed that to the linker.

Followup question: Does this mean that the runtime lookup table contains information about all interfaces in the source of the app regardless of whether linker decided to trim some of the interfaces away?

**Comment by rolfbjarne** [comment]
> Since we're already processing the assembly before linker (to extract the information we inject into native code)

No, our processing happens in a custom linker step, we're not processing anything before the linker. Processing assemblies before the linker is not an option because of performance concerns (loading all the assemblies in memory multiple times from multiple processes can take a significant amount of time).

> Followup question: Does this mean that the runtime lookup table contains information about all interfaces in the source of the app regardless of whether linker decided to trim some of the interfaces away?

No, the table only contains information about interfaces that haven't been linked away.

**Comment by vitek-karas** [comment]
Can the custom step do the marking then?

**Comment by rolfbjarne** [comment]
> Can the custom step do the marking then?

That's what we used to do: https://github.com/xamarin/xamarin-macios/blob/699c1f98fbfb9ac1c5d790a99812aa2f2b1a001b/tools/linker/CoreMarkStep.cs#L162-L168

But that's not possible anymore, because it's not possible for a custom linker step to subclass MarkStep (nor call MarkType).

The workaround I came up with was to not ask the linker to remove the attribute, but instead remove it myself in a custom linker step which executes after the marking phase.

**Comment by vitek-karas** [comment]
@sbomer - is this still needed or we were able to resolve this some other way with the recent work Xamarin/linker integration?

**Comment by sbomer** [comment]
I believe it's not solved yet, but as far as I understand the issue, it could be solved with a custom `IMarkHandler` that is triggered for marked types. Whenever an interface is marked, it could look for `ProtocolAttribute` and keep whatever is needed on the referenced wrapper type. @rolfbjarne does that sound like a reasonable approach? If so I think we could close this and open an issue in xamarin-macios.

**Comment by rolfbjarne** [comment]
@sbomer yes, I believe that would work.
