### ISSUE TITLE
Serializable dependencies are always marked

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#1603]
The [code](https://github.com/mono/linker/blob/master/src/linker/Linker.Steps/MarkStep.cs#L1478) inside linker which checks for a need to mark serializable dependencies fires every time it sees serializable type. This is wasteful and brings a lot of unnecessary dependencies. There should be a better way for the linker to keep the constructors only when they are needed.

@vitek-karas @MichalStrehovsky for their thoughts

**Comment by MichalStrehovsky** [comment]
I think we should just stop doing it. Keeping that constructor increases the chances of the type being serializable, but if we're doing member level trimming, chances are we removed other stuff that was needed. Even if we do our best effort here (try to find a heuristic for when this is needed, or keep the code in place), there are going to be warnings and end users won't be able to reliably combine these serializers with trimming. Linker is not capable of analyzing things for the purposes of BinaryFormatter/DataContractSerializer and friends right now.

If the other problems with serializers are solved (which properties/fields do we need to keep?), the solution for constructors will naturally fall out from that approach.

**Comment by marek-safar** [comment]
This hits the problem where we trim more than is needed in "library-build" mode again. We have several occurrences of serialization ctor which are private.

I'd rather avoid adding another option like --mark-always-ctors for this code pattern. The alternatives are

1. Add a long time due new trim mode described in #1610 and keep any such ctors in this mode based on method signature.

2. Add logic that will keep the ctors when deserialization logic is needed. This is more complicated as it expects that the logic is detected/marked in libraries mode which I'm not sure we can guarantee with `--skip-unresolved` option.

@vitek-karas the option #1 sounds better to me.

**Comment by vitek-karas** [comment]
Option 1 is definitely the simpler one.

**Comment by marek-safar** [comment]
Not only simple but unless we decide to always mark all types for serialization when linking the logic cannot be used for libraries build.

**Comment by eerhardt** [comment]
Could we base the setting on the feature switch introduced in https://github.com/dotnet/runtime/pull/38963? If this feature switch is set, we should be able to safely remove any serialization constructors.

cc @stephentoub

**Comment by MichalStrehovsky** [comment]
> Could we base the setting on the feature switch introduced in dotnet/runtime#38963? If this feature switch is set, we should be able to safely remove any serialization constructors.

At this point this is just a problem for the library build mode - what this issue is tracking is removing special casing in linker that keeps default constructor and the SerializationInfo/StreamingContext constructor when a type is serializable. Feature switches won't help since we don't set them during library build.

During app build, linker should feel free to delete these methods. It's going to delete fields and properties anyway so it's not like BinarySerialization would work if we were to keep these ctors.

During library build, we can't touch them because this is another instance of the "this is public surface area, but not really public surface area" - it's the same problem as SafeHandle constructors. We fixed the SafeHandle constructors problem by making them public...

**Comment by marek-safar** [comment]
Yep, Michal is right. This is libraries build problem only right now. I have ongoing patch which addressess this so will try to push it soon.
