### ISSUE TITLE
Incorrect error message IL2070

### ISSUE THREAD

**Issue by stephentoub** [mono/linker#1616]
I have the following method:
```C#
private ConstructorInfo? GetDefaultConstructor(Type type) =>
    type.IsValueType ? null :
    type.GetConstructor(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly, null, Type.EmptyTypes, null);
```
This is resulting in the following linker error:
```
Trim analysis error IL2070: System.Xml.Serialization.ReflectionXmlSerializationReader.GetDefaultConstructor(Type): The requirements declared via the 'DynamicallyAccessedMembersAttribute' on the parameter 'type' of method 'System.Xml.Serialization.ReflectionXmlSerializationReader.GetDefaultConstructor(Type)' don't match those on the implicit 'this' parameter of method 'System.Type.GetConstructor(BindingFlags,Binder,Type[],ParameterModifier[])'. The source value must declare at least the same requirements as those declared on the target location it's assigned to
```
It's talking about an attribute on the `type` parameter of this method, but... there is no attribute on the type parameter of that method.  If it's intending to say there needs to be one, it should say so, as otherwise it's misleading and confusing referring to an attribute that doesn't exist.

**Comment by mateoatr** [comment]
> it's misleading and confusing referring to an attribute that doesn't exist

Agreed. Would `The parameter 'type' of method 'System.Xml.Serialization.ReflectionXmlSerializationReader.GetDefaultConstructor(Type)' must be annotated with the 'DynamicallyAccessedMembersAttribute' matching the access requirements of the implicit 'this' parameter of method 'System.Type.GetConstructor(BindingFlags,Binder,Type[],ParameterModifier[])'. The source value must declare at least the same requirements as those declared on the target location it's assigned to.`
 make sense here? Asking before updating all places in ReflectionMethodBodyScanner where we have similar warning messages.

/cc @sbomer

**Comment by sbomer** [comment]
I like that a lot better, but I think we should state it in terms of what's wrong, not how to fix it (this seems more consistent with the C# error messages). How about "is not annotated with" instead of "must be annotated with"? I think the second sentence "must declare at least..." is OK because it's clarifying the first part, and I can't come up with a clearer way to say it.

I'm also wondering if we should change the order of the message. Right now you have to scroll past `The requirements declared via the 'DynamicallyAccessedMembersAttribute' on the parameter 'type' of method 'System.Xml.Serialization.ReflectionXmlSerializationReader.GetDefaultConstructor(Type)'` to get to the important part - `don't match`.

In a Roslyn analyzer (with accurate source info) I'd imagine a message like `'this' argument does not satisfy 'DynamicallyAccessedMembers.Whatever'`. The location of the warning would tell you the callsite, so it doesn't need to spell out the source/target. However, we don't necessarily have source line info, and we need to disambiguate errors where multiple different sources flow to the same target. So how about:

`'this' argument does not satisfy 'DynamicallyAccessedMembers.Whatever' in call to 'System.Type.GetConstructor(BindingFlags,Binder,Type[],ParameterModifier[])'. The parameter 'type' of method 'System.Xml.Serialization.ReflectionXmlSerializationReader.GetDefaultConstructor(Type)' does not have matching annotations.`

This puts the immediate problem (`does not satisfy`) near the beginning of the message while still including information about where the argument came from. Does that seem reasonable, or is the reversal confusing?

/cc @vitek-karas
