### ISSUE TITLE
Debug.Assert in DebuggerDisplayAttribute being tripped

### ISSUE THREAD

**Issue by mrvoorhe** [mono/linker#1627]
A developer was using a debug build of our linker and hit this assert https://github.com/mono/linker/blob/8ee2557ccbaf9e4cf243f15b8cb95da4eddb18aa/src/linker/Linker.Steps/MarkStep.cs#L1767

I don't have any more information since Debug.Assert doesn't include potentially helpful information such as the CustomAttribute being processed.

**Comment by sbomer** [comment]
I think we can get rid of the assert. I believe I originally added it because this walks up the base types without marking the generic parameters in case the base is a generic instantiation - but marking fields/methods should take care of this already. I don't think it can cause problems unless the type has no fields/methods, which should never happen.

**Comment by mrvoorhe** [comment]
Thank you
