### ISSUE TITLE
Allow RequiresUnreferencedCode on enum values

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1743]
`System.Data.DataSet` has a `SerializationFormat RemotingFormat` which has two values:

* Xml
* Binary

`Xml`, the default, is implemented in a trim compatible way. But `Binary` uses the `BinaryFormatter` class, which is not trim compatible.

In order to model this in the API, we should allow for `RequiresUnreferencedCodeAttribute` to be applied to the `Binary` enum value. So if someone sets `DataSet.RemotingFormat = SerializationFormat.Binary`, they get an ILLink warning.

@agocke @vitek-karas @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
At the IL level, `DataSet.RemotingFormat = SerializationFormat.Binary` looks more like `DataSet.set_RemotingFormat(2)` (the fields on the enum that define the constant values are not referenced from IL).

Does `if (format == SerializationFormat.Binary)` also mean that we `RequireUnreferencedCode`? Placing the value on the enum itself feels a bit ambiguous to me as to when it applies. "Whenever I use the value in C#" might be one of the interpretations but it's hard to enforce at the IL level.

What might work is to allow annotating integer/enum parameters on methods/setters as "requires unreferenced code if the value is X or Y". This would warn for the value of X/Y/unknown at the callsite.

**Comment by vitek-karas** [comment]
Hmm - that sucks - I didn't realize that enums effectively disappear at IL level. That said - for example ILSpy can mostly figure this out for method calls. The parameter is declared as the enum (even at IL level) and we could lookup the value passed in on the enum to deduce which enum value was used. It's not as precise as in C#, but it's very close and would probably work for this purpose.

**Comment by agocke** [comment]
Also no problem for the analyzers, so it would provide some value there.

**Comment by MichalStrehovsky** [comment]
I think it will lead us to having different warnings generated from the Roslyn analyzer vs illink because the Roslyn's view of "this enum value is used" is different. I still think it's not the enum value that's dangerous, but passing the value into a specific method is.

We should think whether there's more use cases for this. The binary formatter is going to be [obsoleted soon](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md) anyway.

We could just mark the `RemotingFormat` property setter as RequiresUnreferencedCode. The default value of this property is XML so whoever is touching this property is either touching it unnecessarily, or going into danger zone.

**Comment by eerhardt** [comment]
> We could just mark the RemotingFormat property setter as RequiresUnreferencedCode. The default value of this property is XML so whoever is touching this property is either touching it unnecessarily, or going into danger zone.

I think that would work for this specific instance, but it isn't a generalized solution to the problem. For example, if there were 3 enum values, 2 of them were "safe" and 1 was not.

That being said, from reading https://github.com/dotnet/runtime/issues/39289, it sounds like the `SerializationFormat.Binary`  option might be obsoleted and removed eventually anyway. So this specific scenario might get resolved for other reasons.

**Comment by vitek-karas** [comment]
If BinaryFormatter is the only use case then we should probably wait for another use case to look into this some more.
Closing for now (feel free to reopen if we have another use case).
