### ISSUE TITLE
Linker is not opportunistically trimming unused fields from explicit-layout structs

### ISSUE THREAD

**Issue by GrabYourPitchforks** [mono/linker#1883]
Based on a comment at https://github.com/dotnet/runtime/pull/49373#issuecomment-796328576. Imagine you have a struct laid out in this fashion.

```cs
[StructLayout(LayoutKind.Explicit, Size = ...)]
internal struct MyStruct
{
    [FieldOffset(...)]
    int SomeField;

    [FieldOffset(...)]
    int SomeUnusedField;
}
```

If _SomeUnusedField_ is never referenced, it should be able to be safely trimmed from the application. This is because removing the unused field will not reorder other fields in the struct (since they all use _FieldOffset_), not will removing the field affect the overall size of the struct itself (since it has a fixed _Size_ annotation). Currently the trimmer is not taking this opportunity to trim such unused fields.

Edit: This assumes ValueType.Equals and ValueType.GetHashCode are not being called.

**Comment by MichalStrehovsky** [comment]
It can change the alignment of the struct. It would actually change it for your use case in https://github.com/dotnet/runtime/pull/49373 because Vector128 does have pretty significant alignment requirements.

```csharp
unsafe
{
    Console.WriteLine(sizeof(Bar));
}

[StructLayout(LayoutKind.Sequential)]
struct Bar
{
    private int _i;

    private Foo _foo;
}

[StructLayout(LayoutKind.Explicit, Size = 128)]
struct Foo
{
    [FieldOffset(0)]
    private Vector128<byte> _vector;
}
```

Above prints 144, but if I comment out the _vector field, it prints 132.

The field could _probably_ be trimmed if the struct is not a field of any other struct/class, not an element of an array, etc., but it's definitely danger zone. The way the struct is used in your pull request would probably disqualify it from this optimization.

**Comment by GrabYourPitchforks** [comment]
Well, crud. I had forgotten about alignment concerns. :(

**Comment by GrabYourPitchforks** [comment]
BTW, thank you for the informative example! Much appreciated. 👍

**Comment by MichalStrehovsky** [comment]
> BTW, thank you for the informative example! Much appreciated. 👍

:) I assume that since it was you who opened the issue, I could have just responded with "It can change the alignment requirements of the struct." and you would 100% know what I'm taking about, but I tend to write longer responses in case others who have less experience with memory layouts read it and could benefit from an example. Overhearing conversations is how I learn a lot of things myself.
