### ISSUE TITLE
Consider turning off serialization discovery by default

### ISSUE THREAD

**Issue by sbomer** [mono/linker#2924]
https://github.com/dotnet/linker/pull/1932 introduced heuristics to discover and preserve serialized types, for backwards compatibility in xamarin scenarios. The heuristics give no correctness guarantees and will not prevent warnings when using reflection-based serializers (but the xamarin SDK turns off trim warnings globally).

https://github.com/dotnet/runtime/issues/72910 tracks porting this logic to NativeAot for parity with the linker. Could we instead turn off the serialization discovery (maybe with `<TrimMode>full</TrimMode>`) by default, and only use it for the xamarin scenarios?

@MichalStrehovsky @vitek-karas @agocke

**Comment by vitek-karas** [comment]
+1 on disabling this in the "full" mode. It already is effectively a "partial" feature, so it should be tied to the "partial" mode :-)

**Comment by vitek-karas** [comment]
"ability to turn this on outside of xamarin" - what is the UX to do that? If it's only by modifying command line options for the linker I would completely ignore that. If we have an msbuild property for it (I definitely hope we don't) then it's a tiny bit more problematic. But in general I agree with your statement:
There's no guarantee about trimming behavior being the same between linker and AOT, there are already existing differences. Typically AOT is more aggressive in trimming (sometimes because linker can't be that aggressive, but mostly because AOT is just better at it).

**Comment by vitek-karas** [comment]
Sorry I forgot about the partial setting. I still think it's OK. We can add it to NativeAOT if it becomes a bigger problem.

**Comment by MichalStrehovsky** [comment]
The issue is just that if this is a _documented trimming feature_ - that even if you use the serializers with warnings all over the place, but adhere to the documented guidelines, things might work for you just fine, we might need it for NativeAOT.

If it's not a documented trimming feature, but just a compat quirk for Xamarin, we might want to put `<_ExtraTrimmerArgs>--enable-serialization-discovery</_ExtraTrimmerArgs>` into the Xamarin SDK.

I agree that we don't have to worry about random side effects that make things work with illink but fail with NativeAOT in code that is generating warnings in general.

**Comment by vitek-karas** [comment]
I assume we did an announcement about the change in default trim mode. I think that should be enough.
