### ISSUE TITLE
ILLink.Tasks fails on latest dotnet sdk

### ISSUE THREAD

**Issue by ericstj** [mono/linker#442]
Using the 3.0 dotnet SDK, create a new project and add a reference to the latest illink.tasks.

```
C:\Users\ericstj\.nuget\packages\illink.tasks\0.1.5-preview-1841731\build\ILLink.Tasks.targets(511,11): error MSB4057: The target "_HandlePublishFileConflicts" does not exist in the project.
```

This was broken by https://github.com/dotnet/sdk/commit/1936ebd7307cebd6c5d1d8d699b9844f73b8fb2c /cc @peterhuene @dsplaisted

We either need to react to that change in the SDK or undo it.

This is related to discussion here: https://github.com/dotnet/sdk/issues/2583

**Comment by peterhuene** [comment]
We had a change to revert a related rename (https://github.com/dotnet/sdk/commit/9a14094428190b7e33b59f2177e032156b3abfc7#diff-92f864e58ddeb7c3b6de497a574b58ab), so I wouldn't be oppose to changing this back.

That said, I would really like a better contract between the Core SDK targets and consumers.  It makes it really hard to refactor code when anyone might be using our targets, even "private by naming convention" ones.

**Comment by ericstj** [comment]
>  I would really like a better contract between the Core SDK targets and consumers

Yep, I believe that is what dotnet/sdk#2583 is about.

**Comment by dsplaisted** [comment]
We reverted the previous change because there was an interaction with targets in full MSBuild, and you might mix and match between a new SDK and an older MSBuild version (or vice versa).

In this case, especially since ILLink is still in preview, I think it's more reasonable to react to the rename in the consumer.

Not that we can't undo the rename, but I just wanted to point out that in the previous case we really didn't have a choice, while here we do.

**Comment by ericstj** [comment]
I see.  Is it reasonable to say that you need the latest ILLink and the latest SDK?  Will ILLink need to do anything special to support both SDK projects and old-style projects?

**Comment by marek-safar** [comment]
I am assuming this was resolved some time ago (please reopen if that's not the case)
