### ISSUE TITLE
[blazor] minify dlls

### ISSUE THREAD

**Issue by benaadams** [mono/linker#552]
From https://github.com/aspnet/AspNetCore/issues/9702 by @Lupusa87 

Is it possible to make minified versions for blazor's common dlls, e.g. mscorlib.dll?

Decompilation shows that it contains unnecessary data, e.g. method and parameters infos

![](https://user-images.githubusercontent.com/40779557/56617702-89cc4c00-65ee-11e9-808b-2b1f68731520.png)

Do we really need this large summaries?

Also can we use some minification techniques to make size smaller?
For example shortening variable/method/field/class names.

We can have regular and minified versions and use them relatively regular for developing and minified for production.
If minification breaks reflection or serialization code developer will decide not to use minified versions.

Does linker do things like this?

I was playing with mono.cecil and did parameter renaming for mscorlib.dll methods with minimum lengh names and got some small improvement in size, without affecting anything and blazor continued work as expected.

I believe we can reduce dlls if implement techniques from web world which concentrates on efficient traffic.

I think dlls size was not so important before blazor and because this it never got aggressive optimization, but now because load time is critical for blazor and dlls should be downloaded each time, size needs to be optimized with all possible ways.

**Comment by marek-safar** [comment]
wasm runs several optimizations already, we could turn this one on (for non-reflection cases)

**Comment by RemiBou** [comment]
Is there any benefit in minification when we can use gzip compression ? Off course removing comments makes sense

**Comment by benaadams** [comment]
> Is there any benefit in minification when we can use gzip compression ?

In js and html a common approach is to use all lowercase for tags, attributes, function names, variables etc as using a single case gives better compression.

**Comment by Lupusa87** [comment]
@marek-safar
> wasm runs several optimizations already, we could turn this one on (for non-reflection cases)

In interpreted mode we download dlls and execute them using mono wasm.

I am not sure how wasm optimizations helps here.

Our purpose is to make dlls as small as possible, because full AOT mode (where we don't download any dll) will not be soon and for coming mixed (interpreted +aoted) mode we still need to download some dlls.

**Comment by benaadams** [comment]
> I am not sure how wasm optimizations helps here.

The linker can prepare the dlls stripping them of comments; that's an optimization.

**Comment by Lupusa87** [comment]
@RemiBou 
> Is there any benefit in minification when we can use gzip compression ? Off course removing comments makes sense

I agree, after dll minification gzip compression ratio can be less (because we shorten often used names) but still it is better if we do our best to make dll as small as possible and gzip will to his job whatever it will be.

**About comments I was probably wrong, they are not presented in dll and decompiler is extracting it from somewhere.**

Still making symbol shortening can have some **small benefit in size** and also it can serve as **source obfuscator** for some point, because any blazor dlls can be decompiled now very easy.
**If develper wants to secure code this minification will make it less readable.**

Obfuscators I tried yet are **breaking** blazor apps.

I am currently woking on [blazor source mangler](https://github.com/Lupusa87/BlazorSourceMangler) (only dlls for blazor apps and libs not another dlls like mscorlib) and have some positive results.

**I am shortening all methods/types/fields/properties/parameters, size reduce is minimal but here my purpose is to uglify blazor code for foreign eyes.**
 
I think it will be great if linker will have some **optional minification functional** and developer will decide/configure to which dlls wants to apply it.

**Comment by Lupusa87** [comment]
This is no sense, you can close this issue.

Sorry for extra noise.

**Comment by marek-safar** [comment]
>Decompilation shows that it contains unnecessary data, e.g. method and parameters infos

I think this is just the decompiler trying to be smart, the actual data are not in the assembly.

>For example shortening variable/method/field/class names.

Yes, linker does this kind of things but they need to be enabled by the consumers/tools in this case. Some of the additional tricks are tracked at #754
