### ISSUE TITLE
PublishReadyToRun has a negative impact on PublishTrimmed 

### ISSUE THREAD

**Issue by Symbai** [mono/linker#677]
Using PublishTrimmed on a blank WPF project reduces the size from 305 to 243 while using  PublishTrimmed in combination of PublishReadyToRun only reduces the size from 305 to 294. Is there room for improvement?

**Comment by sbomer** [comment]
@Symbai the 3.0 SDK linker defaults are to root assemblies other than netcoreapp, which means that large frameworks like WPF will be rooted by the linker, and since WPF depends on a large part of netcoreapp, the size benefits for WPF apps if you use `PublishReadyToRun` are marginal out of the box. We're thinking about ways to improve this such as providing more aggressive linker options (see https://github.com/mono/linker/issues/624), though we need to be careful since even the conservative defaults are breaking some WPF apps. I'm closing this for now since I believe the ask is captured in various other work that we're tracking, but feel free to re-open if you have questions:
- https://github.com/mono/linker/issues/624 for more aggressive trimming
- https://github.com/mono/linker/issues/712 for WPF config files
- https://github.com/mono/linker/issues/676 for C++/CLI assemblies (esp. those used in WPF)
- https://github.com/mono/linker/issues/761 for a common problem with WPF apps which we will need to address
