### ISSUE TITLE
Error _HandlePublishFileConflicts does not in latest net core sdk

### ISSUE THREAD

**Issue by ammard2u** [mono/linker#753]
hi,
I'm getting this error to publish 
0.1.5-preview-1841731\build\ILLink.Tasks.targets(511,11): error MSB4057: The target "_HandlePublishFileConflicts" does not exist in the project. 

net core version - 3.0.100-rc1-014190
Illink.task version - 0.1.5-preview-1841731

**Comment by dmarlow** [comment]
It worked for me by renaming that to `_HandlePackageFileConflictsForPublish`

**Comment by sbomer** [comment]
@ammard2u the out-of-band ILLink.Tasks package is no longer supported since the linker comes with the 3.0 SDK (which was done specifically because the package kept hitting issues like this due to drift in the SDK). Please see https://aka.ms/dotnet-illink for instructions - essentally, set `PublishTrimmed` to `true` instead of adding the package reference.
