### ISSUE TITLE
Custom steps cannot be resolved from external assembly in ILLink

### ISSUE THREAD

**Issue by mateoatr** [mono/linker#969]
Currently, whenever a user tries to add a custom step to the linkers pipeline, the Driver will [try to retrieve the type](https://github.com/mono/linker/blob/b577649961239131e21288aa6b826a1e2bd92674/src/linker/Linker/Driver.cs#L646) of the custom step that was passed to the linker using the `--custom-step` flag, and fail, since there's no way for the linker to know in which assembly this type is. We should define the way in which the linker should find and resolve custom steps that are passed to it through the command line.

**Comment by vitek-karas** [comment]
To clarify: The custom step can specify the assembly as the type name of the step is supposed to be an assembly qualified name. So it was left to the runtime to find the assembly on disk by its simple name. In .NET Framework and Mono this is not a big problem as both runtimes have a probing mechanism to look for assemblies on disk at least to some extend. In .NET Core this doesn't work because the runtime does no probing on disk by default.

So the ask here should be to define a way to specify the filepath to the assembly in which in the custom step is located, so that the linker/runtime can load it.

**Comment by mateoatr** [comment]
I think that for now we could simply add the full path of the assembly needed after the type name of the custom step. Something like: `--custom step <custom_step_type_name> (<assembly_path>)`.
